### ISSUE TITLE
Key Error: ResBlock_CBAM

### ISSUE THREAD

**Issue by nramelia2** [phd-benel/yolov8_gold#1]
Hello, can I ask about some of the new modules used in this yolov8 upgrade? I tried running it on google colab and it worked but if I run it on the server, I get this error:

Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 419, in entrypoint
    model = YOLO(model, task=task)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 95, in __init__
    self._new(model, task)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 131, in _new
    self.model = (model or self._smart_load('model'))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 232, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 678, in parse_model
    m = getattr(torch.nn, m[3:]) if 'nn.' in m else globals()[m]  # get module
KeyError: 'ResBlock_CBAM'

or maybe I need to install something first? Thank you.

**Comment by phd-benel** [comment]
Hello, first of all thank you for your interest in this project. As far as I know, it seems that the error you are experiencing is due to your local Python directing to the package "/usr/local/lib/python3.10/dist-packages/ultralytics/". However, this package does not contain the new modules that you require. The new modules are in the ultralytics folder that you download from this repository: https://github.com/phd-benel/yolov8_improved_exp.

To resolve this, I recommend the following solution (though it may not be the most optimized approach):

Replace the existing folder "/usr/local/lib/python3.10/dist-packages/ultralytics/' with this one "yolov8_improved_exp/ultralytics". 

By doing so, the issue should be resolved.

If you have any further questions or concerns, please do not hesitate to reach out.
Peace be upon you .

**Comment by nramelia2** [comment]
I think because of this message on the server, there is an error in the module. 

[Errno 2] No such file or directory: '{HOME}'
/workspace/thesis_amel2
Cloning into 'yolov8_improved_exp'...
remote: Enumerating objects: 13246, done.
remote: Total 13246 (delta 0), reused 0 (delta 0), pack-reused 13246
Receiving objects: 100% (13246/13246), 6.20 MiB | 11.71 MiB/s, done.
Resolving deltas: 100% (9159/9159), done.
[Errno 2] No such file or directory: '/content/yolov8_improved_exp'
/workspace/thesis_amel2
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///workspace/thesis_amel2
ERROR: file:///workspace/thesis_amel2 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: python -m pip install --upgrade pip

I feel like it's because there's no setup.py, but I haven't found a solution yet. If you know if you can tell me, I would be very happy. 

Then, can you give me a reference to read about the improved module? Because I haven't found any information about the simFusion example. Thank you.

**Comment by phd-benel** [comment]
Hello,

First, to facilitate the replication of the code on your server, I recommend the following steps:

Navigate to your working directory, for instance, /workspace/thesis_amel2.
then execute the following command in your command prompt: 
pip uninstall ultralytics
then :
git clone https://github.com/phd-benel/yolov8_improved_exp.git
then: 
cd yolov8_improved_exp
then : 
python setup.py develop

By doing so, the issue should be resolved. 

Second, the improved components of YOLOv8-gold were derived from the following sources: the GOLD-YOLO paper available at https://arxiv.org/pdf/2309.11331v5.pdf and the associated source code repository found at https://github.com/huawei-noah/Efficient-Computing/tree/master/Detection/Gold-YOLO. GOLD-YOLO is built upon the YOLOv6 architecture, in contrast to this repository which is based on YOLOv8.

Thirdly, it's important to point out that there's a difference between what's explained in the paper and what's actually written in the code. The names of the modules are not the same. For instance, the "simfusion" module is in the code but not mentioned in the paper. In the code, each module is given a different name compared to what's used in the paper. To make this distinction clearer, here are two figures. The first one uses the names from the code, and the second one uses the names from the paper.

![image](https://github.com/phd-benel/yolov8_gold/assets/82882383/df8c153c-f63b-4b40-aba9-5eb152faea75)
![image](https://github.com/phd-benel/yolov8_gold/assets/82882383/fef37825-98de-4d94-a770-e2827d33e4db)

The mappings between the two figures are as follows:

"SimFusion 4" corresponds to "low_FAM."
"PyramidPoolAgg" corresponds to "high_FAM."
"TopBasicLayer" corresponds to "high_IFM."
...

You can find the complete list of correspondences in the following page : https://github.com/huawei-noah/Efficient-Computing/blob/d76de8db2cd38b228f2ec59b23abf1857793117b/Detection/Gold-YOLO/gold_yolo/reppan.py#L9

Peace be upon you .

**Comment by nramelia2** [comment]
Thanks for the help, it works great.

**Comment by phd-benel** [comment]
You'r welcome.
