### ISSUE TITLE
YOLOv8-gold

### ISSUE THREAD

**Issue by luziao** [phd-benel/yolov8_gold#2]
Hello, is the NECK part of yolov8-gold structure diagram you proposed wrong?

**Comment by phd-benel** [comment]
Hello,

First of all, thank you for your interest and I apologize for the delayed response. From what I understand, the neck structure is correct; it's just the names of the modules that have changed compared to the original paper. You can check out this issue (https://github.com/phd-benel/yolov8_gold/issues/1) for more details and clarification.

Thank you.
